version: '3'

services:
  web:
    build: .
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ressipy_prod
      - FLY_REDIS_CACHE_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=c49jNq1eMqLEXvEkUlkZ4yHUUX0X+q0gGjoBnKF+HOYE0mMtf0Wd+eQGikpJoa/z
      - SENDGRID_API_KEY=abcd1234
    depends_on:
      - postgres
      - redis

  db:
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ressipy_prod
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    image: 'redis:7.0-alpine'
    ports:
      - 6379:6379
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
