version: '2'

services:
  web:
    build: .
    ports:
      - '127.0.0.1:4000:4000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@ressipy_postgres_1:5432/ressipy_prod
      - FLY_REDIS_CACHE_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=c49jNq1eMqLEXvEkUlkZ4yHUUX0X+q0gGjoBnKF+HOYE0mMtf0Wd+eQGikpJoa/z
      - SENDGRID_API_KEY
    depends_on:
      - postgres
      - redis

  postgres:
    image: 'postgres:12'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
