version: '3.8'

services:
  web:
    build: .
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://postgres:@host.docker.internal:5432/ressipy_prod
      ECTO_IPV6: false
      SECRET_KEY_BASE: c49jNq1eMqLEXvEkUlkZ4yHUUX0X+q0gGjoBnKF+HOYE0mMtf0Wd+eQGikpJoa/z
      SENDGRID_API_KEY: abcd1234
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ressipy_prod
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 5

volumes:
  pgdata:
