# fly.toml app configuration file generated for ressipy on 2023-05-27T22:16:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ressipy"
primary_region = "dfw"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/entry eval Ressipy.Release.migrate"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
